#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression --message="Loading settings..." --weight=1

# Get the admin email address
email=$(ynh_user_get_info --username=$admin --key=mail)
# Get the timezone
timezone=$(timedatectl show --value --property=Timezone)

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

ynh_app_setting_set --key=php_upload_max_filesize --value=100M
ynh_app_setting_set --key=php_post_max_size --value=100M
ynh_app_setting_set --key=php_memory_limit --value=512M

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="config.inc.sample.php" --destination="$install_dir/config.inc.php"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a PHP-FPM config (with conf/extra_php-fpm.conf being appended to it)
ynh_config_add_phpfpm

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Install locale
if [[ "${language}" != "en_US" ]]; then
    sudo locale-gen "${language}.UTF-8"
    sudo update-locale
fi

#=================================================
# SETUP APPLICATION
#=================================================
ynh_script_progression "Setting up the application..."

ynh_psql_db_shell <<< "SET ROLE ${db_user}; $(<${install_dir}/rosariosis.sql)"

if [[ -e "${install_dir}/locale/${language}.utf8/rosariosis.sql" ]]; then
    ynh_psql_db_shell <<< "SET ROLE ${db_user}; $(<${install_dir}/locale/${language}.utf8/rosariosis.sql)"
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
